sylius_ui:
    events:
        sylius.admin.channel.create.form:
            blocks:
                product_samples:
                    template: "@BabDevSyliusProductSamplesPlugin/Admin/Channel/_product_samples_form.html.twig"
                    priority: 0

        sylius.admin.channel.update.form:
            blocks:
                product_samples:
                    template: "@BabDevSyliusProductSamplesPlugin/Admin/Channel/_product_samples_form.html.twig"
                    priority: 0

        sylius.shop.layout.javascripts:
            blocks:
                request_a_sample_javascript:
                    template: "@BabDevSyliusProductSamplesPlugin/Shop/JavaScript/_request_a_sample.html.twig"
                    priority: 0
