sylius_ui:
    events:
        sylius.admin.channel.create.form:
            blocks:
                product_samples:
                    template: "@BabDevSyliusProductSamplesPlugin/Admin/Channel/_product_samples_form.html.twig"
                    priority: 0

        sylius.admin.channel.update.form:
            blocks:
                product_samples:
                    template: "@BabDevSyliusProductSamplesPlugin/Admin/Channel/_product_samples_form.html.twig"
                    priority: 0

        sylius.shop.product.show.right_sidebar:
            blocks:
                request_sample:
                    template: "@BabDevSyliusProductSamplesPlugin/Shop/Product/Show/_request_sample.html.twig"
                    priority: 9
