sylius_ui:
    events:
        sylius.admin.channel.form.second_column_content:
            blocks:
                product_samples:
                    template: "@BabDevSyliusProductSamplesPlugin/Admin/Channel/_product_samples_form.html.twig"
                    priority: 0
